version: '3'
services:
  # node:
  #   command: npm run start
  #   environment:
  #     NPM_INSTALL: DISABLE
  #     TYPEORM_MIGRATION: ENABLE
  #   ports:
  #     - 3000:3000

  postgres:
    environment:
      - POSTGRES_USER=auth_db_user
      - POSTGRES_PASSWORD=auth_db_pass
      - POSTGRES_MULTIPLE_DATABASES="auth-dev-db","auth-test-db"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - auth_service_data:/data/postgres
    ports:
      - 5436:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=auth_service@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  auth_service_data: {}
  pgadmin:
